appId: com.factulite.client
productName: FactuLite Client
copyright: Copyright 2025 FactuLite

directories:
  output: dist
  buildResources: build

asar: true

files:
  - src/**/*
  - package.json

win:
  target:
    - target: nsis
      arch:
        - x64

nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: FactuLite Client
  artifactName: FactuLite-Client-Setup-${arch}.exe
  deleteAppDataOnUninstall: false
